version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: postgres-container
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        networks:
            - db_network

    mongodb:
        image: mongo:latest
        container_name: mongodb-container
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        networks:
            - db_network

networks:
    db_network:
        driver: bridge