version: '3'

services:
    postgres-service:
        container_name: postgres-container
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=sa_db
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=pass
        networks:
            - app_network
        volumes:
            - postgres-volume:/var/lib/postgresql/data

    mongo-service:
        container_name: mongo-container
        image: mongo:latest
        ports:
            - "27017:27017"
        networks:
            - app_network
        volumes:
            - mongo-volume:/data/db

    app-service:
        container_name: app-container
        build:
            context: .
            args:
                JDK_VERSION: 11
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - POSTGRES_URL=jdbc:postgresql://postgres-service:5432/sa_db
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=pass
            - MONGODB_URI=mongodb://mongo-service:27017/sa_db
            - JWT_SECRET_KEY=3673f827897f5dd46806cc0463f6486738d6d039adca0e5adeef1dcd3deb7048d085f98ec575e754c5d8c675bc35ad6d847b355bd2a96a57b4249db758f2172face19f715e77add2bd58e56cf6ef349c139b878106ffb06f642d911b8165750be28078a23d7da6f9d632fbdaf1680fb8d056e7b8895174fc892ff1548c71d2f923bbadff58453327d12177528522b762303ad7635693c557b48a1a7d43b5c638ff52e5566f6a37f801f9dc2157482ceca4ad2d823c48a93844e1c7946c65be7fcb763a54ca6690dd59190bb02fa359ff69dc2a9c1679083ef73bb91cd3385438092003b58ac8a5777ac83af76bb6db673d662a7ca0b23e9e3d338a89b41191fc
        networks:
            - app_network
        depends_on:
            - postgres-service
            - mongo-service

networks:
    app_network:
        driver: bridge

volumes:
    postgres-volume:
    mongo-volume: