spring:
    data:
        mongodb:
            uri: mongodb://localhost/testdb
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: pass
    mongodb:
        embedded:
            version: 4.0.2
    jpa:
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.H2Dialect