spring:
    application:
        name: sa_task_04_06
    data:
        mongodb:
            uri: mongodb://localhost:27017/sa_db
            username: admin
            password: pass
    datasource:
        url: jdbc:postgresql://localhost:5430/sa_db
        username: postgres
        password: pass
    jpa:
        hibernate:
            ddl-auto: update

app:
    config:
        security:
            jwt:
                secret_key: ${JWT_SECRET_KEY}